version: '3.8'
services:
  postgres:
    image: postgres:15.3-alpine
    container_name: desafio
    restart: always
    environment:
      POSTGRES_PASSWORD: 123456789
      POSTGRES_USER: postgres
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass 1234567
    volumes:
      - cache:/data

volumes:
  cache:
    driver: local
